### ISSUE TITLE
Validation error specific to resolving `dict` 

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#105]
Update: potential edge case  / bug in Hydra

```python
def f(x): return x

instantiate(builds(f, list))  # ok
instantiate(builds(f, str))  # ok
instantiate(builds(f, int))  # ok
instantiate(builds(f, len))  # ok
instantiate(builds(f, f))  # ok

instantiate(builds(f, x=dict))  # ok
instantiate(builds(f, dict))  # ValidationError: Unsupported value type: <class 'dict'>

```

This all gets handled by the same code:

https://github.com/mit-ll-responsible-ai/hydra-zen/blob/cff79a7370e5c2a06e19208bbd351aa1a2296f81/src/hydra_zen/structured_configs/_implementations.py#L703-L713

**Comment by Jasha10** [comment]
This works:
````python
>>> instantiate(builds(f, dict), _convert_="all")
<class 'dict'>
```

**Comment by Jasha10** [comment]
In the case where the default value `_convert_="none"` is used: As the `instantiate` function traverses the config tree, instantiating the leaf nodes and working it's way towards the root in a depth-first manner, intermediate values are wrapped in OmegaConf containers (`DictConfig` and `ListConfig`) as applicable.
Meanwhile, if `_convert_="all"` is used then no such wrapping is done.

As to the issue with `instantiate(builds(f, dict))`:
The `builds(f, dict)` dataclass results in a `DictConfig` object that looks like this:
```
{'_target_': '__main__.f', '_args_': [{'_target_': 'hydra_zen.funcs.get_obj', 'path': 'builtins.dict'}]}
```
In the process of visiting the lower levels of this tree, there is at some point a partially-instantiated state that something like this:
```
{'_target_': '__main__.f', '_args_': [dict]}
```

I believe that, given `_convert_="none"`, the `ValidationError` occurs when the `[dict]` part is supposed to be wrapped as a `ListConfig` object. In fact, all three of the following fail with the same error and for the same reason:
```
instantiate(builds(f, dict))
OmegaConf.create([dict])
OmegaConf.create(dict)
```
Whether `OmegaConf.create(dict)` *should* fail (or what it's expected behavior should be if it is not to fail) is debatable, but anyway I think that `_convert_="all"` (and maybe `_convert_="object"` in the future if https://github.com/facebookresearch/hydra/issues/1719 is implemented) may be a sensible default in the context of hydra-zen.

**Comment by rsokl** [comment]
Thanks so much for the detailed insights, @Jasha10 . It occur to me to try changing `builds(f, just, hydra_convert="all")`. 

I came across this when I was putting together some tutorial materials, and wanted to be sure to make note of it before moving on. Fortunately it isn't actually impacting any of my work, and I suspect that this wouldn't come up for many users.

I will open an issue on `omegaconf` to document this, unless you don't think it is worth doing so.

**Comment by Jasha10** [comment]
Ok, sounds good!
Up to you if you want to submit an omegaconf issue :)
