### ISSUE TITLE
Iterative `builds` specification

### ISSUE THREAD

**Issue by petosa** [mit-ll-responsible-ai/hydra-zen#348]
One use case I run into a bit is wanting to define a generic `builds` result, and then iteratively specialize that config for different purposes. Here's an example where I have a generic `DeepNetConfig` that I want to iteratively define. 

```python
import dataclasses

from hydra_zen import builds, instantiate
from omegaconf import MISSING


@dataclasses.dataclass
class NeuralNetwork:
    layers: int = MISSING
    width: int = MISSING
    gpu: bool = MISSING
    

def pp(x):
    print(x, "::", type(x))
    print()
    
# "Base" build
DeepNetConfig = builds(NeuralNetwork, layers=10, populate_full_signature=True)
pp(DeepNetConfig)

# Specialize the build to be a deep network
DeepWideNetConfig = DeepNetConfig(width=100)
pp(DeepWideNetConfig)

# Specialize the deep network to run on GPU
GPUDeepWideNetConfig = DeepWideNetConfig(gpu=True)
pp(GPUDeepWideNetConfig)
```

The above code will fail specifying `GPUDeepWideNetConfig` with `TypeError: 'Builds_NeuralNetwork' object is not callable`. I want to avoid the redundancy of needing to re-specify the parameters for `width` and `layers` when specifying `GPUDeepWideNetConfig`. Any hints on how?

**Comment by rsokl** [comment]
I like this "builder" pattern. The [ZenStore](https://mit-ll-responsible-ai.github.io/hydra-zen/generated/hydra_zen.ZenStore.html#hydra_zen.ZenStore) feature in the upcoming release has this sort of "self-partialing" capability:

```python
from hydra_zen import ZenStore

store= ZenStore()
optim_store = store(group="optim")  # overwrites group default
slow_store = optim_store(lr=1e-6)
fast_store = optim_store(lr=1e-1)

slow_store(SGD)
slow_store(Adam)
fast_store(SGD)
fast_store(Adam)
```

You can enable this capability in `builds` inheriting from a dataclass with a `__call__` method that is able to override the dataclass' args:

```python
from dataclasses import dataclass
from typing import Any
from typing_extensions import Self

@dataclass
class BuilderBase:
    def __call__(self: Self, **kwds: Any) -> Self:
        kw = {k: getattr(self, k) for k in self.__dataclass_fields__ if not k.startswith("_")}
        kw.update(kwds)
        return type(self)(**kw)
```


This works quite nicely when you initialize all of the defaults with `MISSING` as you did in your example, and, surprisingly, there are no type checking errors.

```python
import dataclasses

from hydra_zen import builds, instantiate
from omegaconf import MISSING


@dataclasses.dataclass
class NeuralNetwork:
    layers: int = MISSING
    width: int = MISSING
    gpu: bool = MISSING


def pp(x):
    print(x, "::", type(x))
    print()


# "Base" build -- inherits from BuilderBase
DeepNetConfig = builds(
    NeuralNetwork, layers=10, populate_full_signature=True, builds_bases=(BuilderBase,)
)
pp(DeepNetConfig)

# Specialize the build to be a deep network
DeepWideNetConfig = DeepNetConfig(width=100)
pp(DeepWideNetConfig)

# Specialize the deep network to run on GPU
GPUDeepWideNetConfig = DeepWideNetConfig(gpu=True)
pp(GPUDeepWideNetConfig)

```
```
<class 'types.Builds_NeuralNetwork'> :: <class 'type'>

Builds_NeuralNetwork(_target_='__main__.NeuralNetwork', layers=10, width=100, gpu='???') :: <class 'types.Builds_NeuralNetwork'>

Builds_NeuralNetwork(_target_='__main__.NeuralNetwork', layers=10, width=100, gpu=True) :: <class 'types.Builds_NeuralNetwork'>
```

The only downside that I can see, thus far, is that type checkers can't "see" that `BuilderBase` was inherited from, and thus `GPUDeepWideNetConfig` type checks as `Any` instead of `Builds[...]`. At least this is the case for pyright, mypy might raise. 

To get things to type-check correctly/legibly, I would have to do... a bunch of stuff 😅 . 

Let me know how this solution works for you!

**Comment by petosa** [comment]
Very cool, let me try out the `BuilderBase` pattern and let you know how it goes!

**Comment by petosa** [comment]
You guys are amazing, thank you!
