### ISSUE TITLE
Unnecessary `_target_` field using `store` and `dataclasses`

### ISSUE THREAD

**Issue by jgbos** [mit-ll-responsible-ai/hydra-zen#393]
Found this when creating the example for #389.  The configuration added to the store appears to create an unnecessary `_target_` field to the configuration.

```python
from dataclasses import dataclass

from hydra_zen import store, to_yaml

db_store = store(group="db")
@db_store(name="mysql")
@dataclass
class MySQL:
    name: str = "mysql

print(to_yaml(MySQL))
# Outputs:
# name: mysql 


print(to_yaml(store[("db", "mysql")]))
# Outputs
# name: mysql
# _target_: __main__.MySQL
```

**Comment by rsokl** [comment]
This is due to the fact that `ZenStore.__call__` will automatically apply [default_to_config](https://mit-ll-responsible-ai.github.io/hydra-zen/generated/hydra_zen.wrapper.default_to_config.html#hydra_zen.wrapper.default_to_config) to whatever the target is. In this case, it applies `just` to the decorated dataclass, which enables our [auto-config support for dataclasses](https://mit-ll-responsible-ai.github.io/hydra-zen/changes.html#id7) (e.g. you can decorate a pydantic dataclass and it will instantiate back to the native dataclass).

You can disable this by specifying `to_config=lambda x: x`

```python
from dataclasses import dataclass

from hydra_zen import store, to_yaml

db_store = store(group="db", to_config=lambda x: x)

@db_store(name="mysql")
@dataclass
class MySQL:
    name: str = "mysql"

print(to_yaml(MySQL))
# Outputs:
# name: mysql 


print(to_yaml(store[("db", "mysql")]))
# Outputs
# name: mysql
```
