### ISSUE TITLE
@zen task_function crashes and doesn't return 

### ISSUE THREAD

**Issue by AllanSCosta** [mit-ll-responsible-ai/hydra-zen#399]
Hi folks! 

Fantastic job, loving how clean and fast zen-hydra makes things

I'm looking into first building a configuration into a yaml file, and then reading that file to start a training session:
```
train_config = load_from_yaml("config.yml")
_ = zen(train)(train_config)
```
As I'm prototyping in the fly, the code within main is expected to crash very often. Unfortunately, when `train` finishes or every time it runs into an error the program stops and doesn't seem to return (despite `ctrl+c` or any other signal I send the process). The main problem is that it doesn't return the allocated GPU memory either haha – otherwise would be fine with zombie processes hanging around :)

**Comment by rsokl** [comment]
Thanks for the kind feedback @AllanSCosta !

> The main problem is that it doesn't return the allocated GPU memory either haha – otherwise would be fine with zombie processes hanging around :)

Is this issue specific to the `zen` wrapper, or does it occur when you simply run  your task using Hydra? I ask because `zen` itself doesn't do anything that would impact your process' ability to receive interrupt signals or to free up memory. [As you can see here](https://github.com/mit-ll-responsible-ai/hydra-zen/blob/52085d5b66d1b8528a48533029c69a0e4532a828/src/hydra_zen/wrapper/_implementations.py#L360-L367) it ultimately just calls your underlying task function as-is.

@jgbos  perhaps you have some experience with making Hydra fail more gracefully w.r.t freeing GPU memory.

**Comment by AllanSCosta** [comment]
Ohhh I see. It could then be a Hydra or OmegaConf-specific problem then. I'll dig more into this, will let you know if I find a way around it or run into anything. Thanks! 🙏
