### ISSUE TITLE
Move `OmegaConf.resolve(cfg)` after `pre_call`

### ISSUE THREAD

**Issue by petosa** [mit-ll-responsible-ai/hydra-zen#444]
Hello,

I am using the `@zen` decorator in my project, and using its `pre_call` arg to modify my config. I am trying to modify the unresolved config, but `pre_call` gets the config after `OmegaConf.resolve(cfg)` has been run.
https://github.com/mit-ll-responsible-ai/hydra-zen/blob/796d8ac7c87c5ad245eb739cd27b81cf62eb19ca/src/hydra_zen/wrapper/_implementations.py#L336

Can `OmegaConf.resolve(cfg)` please be moved to be after `self.pre_call(cfg)` to allow for more flexibility?

**Comment by jgbos** [comment]
@petosa I'll think about it (and I'm sure @rsokl will have more insight) but I don't think this is possible in hydra-zen as the resolver is handled by Hydra.  You might want to look into Hydra callbacks: https://hydra.cc/docs/experimental/callbacks/

**Comment by petosa** [comment]
Thanks for your reply. Couldn't the requested change be achieved by moving line 336 in the linked code to line 340?

**Comment by rsokl** [comment]
I like the idea of being able to sue `pre_call` to do stuff to the cfg before it gets resolved. Moving `resolve` is no good because it could easily break people's existing code.

Off the top of my head, I think `Zen`/`zen` should have a `resolve_cfg: bool = True` param. For your desired case, you would disable it and then have your `pre_call` function be responsible for calling `OmegaConf.resolve` at the end.

I would happily accept a PR for this. Our CI seems to need some care due to breaking changes in pydantic and some other flakiness, so be warned that it might be a little noisy. I hope to fix it this weekend.

**Comment by rsokl** [comment]
(CI is back in good health)

**Comment by rsokl** [comment]
@petosa  v0.11.0rc4 added `zen(resolve_pre_call=False)` to address this limitation. Try it out with `pip install --pre hydra-zen`
